<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f1c114f5-f641-4295-94c0-01875e106243</elementGuidId>
    <imagePath></imagePath>
    <name>button_object_2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>:root &gt; :nth-child(2) &gt; :nth-child(1) &gt; :nth-child(3) &gt; :nth-child(4) &gt; :nth-child(1) &gt; :nth-child(2) &gt; :nth-child(1) &gt; :nth-child(2) &gt; :nth-child(1) &gt; :nth-child(2) &gt; :nth-child(5) &gt; :nth-child(1) &gt; :nth-child(1)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'btn btn-outline-secondary text-center')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn-outline-secondary text-center</value>
        <webElementGuid>4b3445ab-4497-4d09-b9cc-d14f487e66cb</webElementGuid>
    </webElementProperties>
</WebElementEntity>